import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next.js practice",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme='light' >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<div className="max-w-screen-2xl mx-auto max-h-screen" >
<Navbar></Navbar>
{children}
</div>
      </body>
    </html>
  );
}
